# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d44a6a9294dd1e645a55745390850651979d9de84d88520399cc11691a038c637fce280d6bcb020b4da791b5bf83650e8f718a5abd28202952dbced12e52aa79

test:
  secret_key_base: a422e05eee3c1183cb11a37d4e04b6c4c8eae57c8e9c5e4a73a446a85372b589f1e6c966a5b99275f4bddeb7a98953a4e5b94e26c42691de570286bfc552f809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
